[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh /usr/local/bin/docker-entrypoint.sh php-fpm"
healthcheckPath = "/api/products"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
